### ISSUE TITLE
Double wooden shelves show as storing Large items when they actually support Extra Large

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/twotech#39]
https://twotech.twohoursonelife.com/8417-Dark-Wooden-Wall-with-Double-Shelf-noBackAccess-useOnContained

https://discord.com/channels/423293333864054833/456031674480853003/1178396584510226442

**Comment by mtklass** [comment]
This was addressed [here](https://discord.com/channels/423293333864054833/456031674480853003/1178565440344170538) and [here](https://discord.com/channels/423293333864054833/456031674480853003/1178566385731911770).

It turns out this was a misunderstanding due to the fact shelves hold triple-crates, which are extra large. But they are the _only_ extra large items that fit on shelves, so twotech should probably still just show it as large.
