### ISSUE TITLE
Add functionality to process a subset of data 

### ISSUE THREAD

**Issue by TanyaPegasus** [twohoursonelife/twotech#44]
Currently data for all objects and sprites is processed every time the program is run. The only way to process select objects is to selectively place them into a new folder. It's also necessary to identify all the required sprites for the object and process those as well.

Feature request to add a way to more easily process only the desired objects and sprites for bug testing etc. This speeds up the time taken considerably.

**Comment by mtklass** [comment]
@TanyaPegasus 

This is more specific, but I did make a process script enhancement that lets you reprocess the sprite(s) for a specific object ID.

So something like this: `npm run process-specific-sprites 3338`
Would regenerate the .png for only the Glass Bottle.

It's on a branch of my fork (no PR yet, since it builds off the Vue3/Typescript work):
https://github.com/mtklass/twotech/tree/parse-specific-object-sprites

**Comment by connorhsm** [comment]
> @TanyaPegasus
> 
> This is more specific, but I did make a process script enhancement that lets you reprocess the sprite(s) for a specific object ID.
> 
> So something like this: `npm run process-specific-sprites 3338` Would regenerate the .png for only the Glass Bottle.
> 
> It's on a branch of my fork (no PR yet, since it builds off the Vue3/Typescript work): https://github.com/mtklass/twotech/tree/parse-specific-object-sprites

I suspect this will satisfy me to close this.

**Comment by connorhsm** [comment]
I'm going to mark this complete thanks to @mtklass 's work.

I am considering whether a future addition may be to also enable processing the data attached to the object, but I don't have an immediate need.
